name: CI

on:
  push:
    branches:
      - msys2

env:
  CARGO_TERM_COLOR: always

jobs:
  msi:
    name: msi
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        version:
          # - "1.8"
          - "1.10"
          # - "1.12"
          # - "1.13"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: {submodules: false}
      - name: Install Rust (${{matrix.rust}})
        uses: actions-rs/toolchain@v1
        with: {toolchain: '${{matrix.rust}}', profile: minimal, override: true}
      - name: Configure environment
        shell: bash
        run: |
          if [[ "${{matrix.version}}" == "1.8" ]]; then
            VERSION=1.8.21
            DL_PATH=hdf5-1.8.21-Std-win7_64-vs14.zip
            echo "MSI_PATH=hdf\\HDF5-1.8.21-win64.msi" >> $GITHUB_ENV
          elif [[ "${{matrix.version}}" == "1.10" ]]; then
            VERSION=1.10.0
            DL_PATH=windows/extra/hdf5-1.10.0-win64-VS2015-shared.zip
            echo "MSI_PATH=hdf5\\HDF5-1.10.0-win64.msi" >> $GITHUB_ENV
          elif [[ "${{matrix.version}}" == "1.12" ]]; then
            VERSION=1.12.0
            DL_PATH=hdf5-1.12.0-Std-win10_64-vs16.zip
            echo "MSI_PATH=hdf\\HDF5-1.12.0-win64.msi" >> $GITHUB_ENV
          else
            VERSION=1.13.0
            DL_PATH=windows/hdf5-1.13.0-Std-win10_64-vs16.zip
            echo "MSI_PATH=hdf\\HDF5-1.13.0-win64.msi" >> $GITHUB_ENV
          fi
          BASE_URL=https://support.hdfgroup.org/ftp/HDF5/prev-releases
          echo "DL_URL=$BASE_URL/hdf5-${{matrix.version}}/hdf5-$VERSION/bin/$DL_PATH" >> $GITHUB_ENV
          echo "C:\\Program Files\\HDF_Group\\HDF5\\$VERSION\\bin" >> $GITHUB_PATH
      - name: Install HDF5 (${{matrix.version}})
        shell: bash
        run: |
          ls C:\msys64
          pacboy find hdf5
      #- name: Build and test all crates
      #  run: cargo test -vv
