name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 18 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  msi:
    name: msi
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        version: ["1.8", "1.10", "1.12.0", "1.12.1"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: {submodules: true}
      - name: Install Rust (${{matrix.rust}})
        uses: actions-rs/toolchain@v1
        with: {toolchain: '${{matrix.rust}}', profile: minimal, override: true}
      - name: Configure environment
        shell: bash
        run: |
          BASE_URL=https://support.hdfgroup.org/ftp/HDF5/prev-releases
          if [[ "${{matrix.version}}" == "1.8" ]]; then
            VERSION=1.8.21
            DL_PATH=hdf5-1.8.21-Std-win7_64-vs14.zip
            echo "MSI_PATH=hdf\\HDF5-1.8.21-win64.msi" >> $GITHUB_ENV
            echo "DL_URL=$BASE_URL/hdf5-${{matrix.version}}/hdf5-$VERSION/bin/$DL_PATH" >> $GITHUB_ENV
          elif [[ "${{matrix.version}}" == "1.10" ]]; then
            VERSION=1.10.0
            DL_PATH=windows/extra/hdf5-1.10.0-win64-VS2015-shared.zip
            echo "MSI_PATH=hdf5\\HDF5-1.10.0-win64.msi" >> $GITHUB_ENV
            echo "DL_URL=$BASE_URL/hdf5-${{matrix.version}}/hdf5-$VERSION/bin/$DL_PATH" >> $GITHUB_ENV
          elif [[ "${{matrix.version}}" == "1.12.0" ]]; then
            VERSION=1.12.0
            DL_PATH=hdf5-1.12.0-Std-win10_64-vs16.zip
            echo "MSI_PATH=hdf\\HDF5-1.12.0-win64.msi" >> $GITHUB_ENV
            echo "DL_URL=$BASE_URL/hdf5-1.12/hdf5-1.12.0/bin/$DL_PATH" >> $GITHUB_ENV
          else
            VERSION=1.12.1
            DL_PATH=windows/hdf5-1.12.1-Std-win10_64-vs16.zip
            echo "MSI_PATH=hdf\\HDF5-1.12.1-win64.msi" >> $GITHUB_ENV
            echo "DL_URL=$BASE_URL/hdf5-1.12/hdf5-1.12.1/bin/$DL_PATH" >> $GITHUB_ENV
          fi
          echo "C:\\Program Files\\HDF_Group\\HDF5\\$VERSION\\bin" >> $GITHUB_PATH
      - name: Install HDF5 (${{matrix.version}})
        shell: pwsh
        run: |
          C:\msys64\usr\bin\wget.exe -q -O hdf5.zip ${{env.DL_URL}}
          7z x hdf5.zip -y
          msiexec /i ${{env.MSI_PATH}} /quiet /qn /norestart
      - name: Build and test all crates
        run: cargo test -vv
