name: CI

on:
  push:
    branches:
      - msys2

env:
  CARGO_TERM_COLOR: always

jobs:
  msi:
    name: msi
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        version:
          # - "1.8"
          - "1.10"
          # - "1.12"
          # - "1.13"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: {submodules: false}
      #- name: Install Rust (${{matrix.rust}})
      #  uses: actions-rs/toolchain@v1
      #  with: {toolchain: '${{matrix.rust}}', profile: minimal, override: true}
      - name: Configure environment
        shell: bash
        run: |
          echo "C:\\msys64" >> $GITHUB_PATH
      - name: Install HDF5 (${{matrix.version}})
        shell: bash
        run: |
          ls C:\\msys64
          echo ""
          ls C:\\msys64\\usr
          pacboy find hdf5
      #- name: Build and test all crates
      #  run: cargo test -vv
