name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  brew:
    name: brew
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {version: hdf5-mpi, mpi: true}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: {submodules: true}
      - name: Install Rust (${{matrix.rust}})
        uses: actions-rs/toolchain@v1
        with: {toolchain: stable, profile: minimal, override: true}
      - name: Install HDF5 (${{matrix.version}})
        run: brew install ${{matrix.version}}
      - name: Build and test all crates
        run: |
          [ "${{matrix.mpi}}" != "" ] && FEATURES=mpio
          cargo test -vv --features="$FEATURES" -j1 || echo ""
      - name: Run build script under valgrind
        run: valgrind /Users/runner/work/hdf5-rust/hdf5-rust/target/debug/build/hdf5-sys-575eea4c73ecfbf4/build-script-build
