name: CI

on:
  push:
    branches:
      - msys2

env:
  CARGO_TERM_COLOR: always

jobs:
  msi:
    name: msi
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [stable-gnu]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: {submodules: false}
      - name: Install Rust (${{matrix.rust}})
        uses: actions-rs/toolchain@v1
        with: {toolchain: '${{matrix.rust}}', profile: minimal, override: true}
      - name: Configure environment
        shell: bash
        run: |
          echo "C:\\msys64\\usr\\bin" >> $GITHUB_PATH
          echo "PKG_CONFIG_PATH=C:\\msys64\\usr\\share\\pkgconfig" >> $GITHUB_ENV
          echo "HDF5_DIR=C:\\msys64\\usr" >> $GITHUB_ENV
      - name: Install HDF5 (${{matrix.version}})
        shell: bash
        run: |
          pacman -S --noconfirm clang64/mingw-w64-clang-x86_64-hdf5
          ls C:\\msys64\\usr\\share\\pkgconfig
          pkg-config --libs --cflags hdf5
      - name: Build and test all crates
        run: cargo test -vv
