name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 18 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  msi:
    name: msi
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {toolchain: "stable-msvc", version: "1.12"}
          - {toolchain: "stable-gnu", version: "1.12"}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: {submodules: false}
      - name: Install Rust (${{matrix.target}})
        uses: actions-rs/toolchain@v1
        with: {toolchain: "${{matrix.toolchain}}", profile: minimal, override: true}
      - name: Configure environment
        shell: bash
        run: |
          if [[ "${{matrix.version}}" == "1.8" ]]; then
            VERSION=1.8.21
            DL_PATH=hdf5-1.8.21-Std-win7_64-vs14.zip
            echo "MSI_PATH=hdf\\HDF5-1.8.21-win64.msi" >> $GITHUB_ENV
          elif [[ "${{matrix.version}}" == "1.10" ]]; then
            VERSION=1.10.0
            DL_PATH=windows/extra/hdf5-1.10.0-win64-VS2015-shared.zip
            echo "MSI_PATH=hdf5\\HDF5-1.10.0-win64.msi" >> $GITHUB_ENV
          else
            VERSION=1.12.0
            DL_PATH=hdf5-1.12.0-Std-win10_64-vs16.zip
            echo "MSI_PATH=hdf\\HDF5-1.12.0-win64.msi" >> $GITHUB_ENV
          fi
          BASE_URL=https://support.hdfgroup.org/ftp/HDF5/prev-releases
          echo "DL_URL=$BASE_URL/hdf5-${{matrix.version}}/hdf5-$VERSION/bin/$DL_PATH" >> $GITHUB_ENV
          echo "C:\\Program Files\\HDF_Group\\HDF5\\$VERSION\\bin" >> $GITHUB_PATH
      - name: Install HDF5 (${{matrix.version}})
        shell: pwsh
        run: |
          C:\msys64\usr\bin\wget.exe -q -O hdf5.zip ${{env.DL_URL}}
          7z x hdf5.zip -y
          msiexec /i ${{env.MSI_PATH}} /quiet /qn /norestart
      - name: Export HDF5_DIR
        if: matrix.toolchain == 'stable-gnu'
        run: echo "HDF5_DIR=C:\\Program Files\\HDF_Group\\HDF5\\1.12.0" >> $GITHUB_ENV
      - name: Build and test all crates
        run: cargo test --workspace -vv --exclude hdf5-src
